export const languageText = {
  'en':  {
    index: `Home`,
    catalog: `Catalog`,
    deliveryPayment: `Payment and Delivery`,
    contacts: `Contacts`,
    forPartner: `Partners`,
    language: `Language`,
    select: `EN`,
    becomePartner: `Become a partner`,
    address: `Territoriya Opytnaya Stantsiya, Alexeyevka, Belgorod Region, Russia, 309856`,
    addressStart: `Territoriya Opytnaya Stantsiya, Alexeyevka`,
    addressEnd: `Belgorod Region, Russia, 309856`,
    production: `Production`,
    ofEssentialOils: `of Essential Oils`,
    essentialOils: `Essential Oils`,
    essentialOil: `Essential Oil`,
    essentialOilStart: `Essential`,
    essentialOilEnd: `Oil`,
    essentialOilsText: `Only high-quality and certified organic essential oils`,
    ofSpices: `of Spices`,
    spices: `Spices`,
    spice: `Spices`,
    spicesText: `We provide a seed cleaning rate of over 99% and offer various grinding fractions`,
    order: `Order now`,
    aboutCompanyTitleStart: `Where Tradition`,
    aboutCompanyTitleEnd: `Meets Quality`,
    aboutCompanyDescription: `15 years of experience in natural products production using modern technologies and complying with high environmental standards`,
    aboutCompanyBlock1: `High-quality standards leading to high-quality products`,
    aboutCompanyBlock2: `Steam distillation method used for our essential oil extraction has proven to be the most effective way of obtaining natural product`,
    aboutCompanyBlock3: `Unique laboratory testing methods provide information on the quality of oils and allow us to make sure no adulteration occurred during the production process`,
    coriander: `Сoriander`,
    corianderStart: `Сori`,
    corianderEnd: `ander`,
    productFormDescription: `Our company can produce essential oil and press cake as well as carry out grinding and purification of any essential oil crops`,
    seeds: `Seeds`,
    pressCake: `Press cake`,
    powder: `Powder`,
    wholesaleTitleStart: `Wholesale`,
    wholesaleTitleEnd: `and Retail`,
    wholesaleDescription: `Customized pricing strategy. Extensive product line supplied in batches with various packaging options — from 10 ml to 180 kg`,
    feedbackIndexTitleStart: `Become`,
    feedbackIndexTitleEnd: `our Partner`,
    feedbackTitleStart: `Become`,
    feedbackTitleEnd: `our Partner`,
    name: `Name`,
    phoneNumber: `Phone number`,
    youMessage: `Type your message here`,
    submit: `Submit`,
    contactUs: `Contact us`,
    howToUse: `Sphere of Application`,
    packaging: `Packaging`,
    certificateOfQuality: `Certificate of Quality`,
    kraftBag: `Kraft Paper Bag`,
    kraftBagCharacteristics: `100-500 g`,
    fleconBag: `Flecon Bag`,
    fleconBagCharacteristics: `up to 20 kg`,
    paperBag: `Paper Bag`,
    paperBagCharacteristics: `up to 25 kg`,
    bigBag: `Big Bag`,
    bigBagCharacteristics: `500-800 kg`,
    powderWomen: `Powder`,
    powderMan: `Powder`,
    topGrade: `Top grade`,
    firstGrade: `1 grade`,
    secordGrade: `2 grade`,
    thirdGrade: `3 grade`,
    glassPackaging: `Glass and Plastic Packaging`,
    glassPackagingCharacteristics: `10 ml-10 kg`,
    steelBarrel: `Steel Barrel`,
    steelBarrelCharacteristics: `up to 180 kg`,
    essentialOilEn: `Essential oil`,
    essentialOilRU: ``,
    footerLogoStart: `Belgorod region export`,
    footerLogoEnd: `support center`,
    required: `Required`,
    deliveryBlock1Start: `Once your order is placed`,
    deliveryBlock1Body: `our manager will contact you within an hour`,
    deliveryBlock1End: `to specify the details.`,
    deliveryBlock2Start: `We deliver`,
    deliveryBlock2End: ` our products to any city in Russia, as well as to near and far-abroad countries. The shipment is carried out by the following delivery companies: CDEK, Business Lines, PEC, and by the means of our truck fleet. We are happy to help you choose the best delivery method.`,
    deliveryBlock3Start: `The shipment`,
    deliveryBlock3End: `is carried out after receiving 100% advance payment within 1-5 working days.`,
    deliveryBlock4Start: `For customers from other countries`,
    deliveryBlock4End: `international bank transfer payment using the SWIFT system is available.`,
    npo: `Scientific & Production Association Alekseevskoe LLC (OOO)`,
    popupSubmitTitle: `Submit your request`,
    popupCheckBox: `I hereby consent to the processing of my personal data for the selected purposes specified in the`,
    popupCheckBoxAnd: `and the`,
    popupPrivacyPolicy: `Privacy Policy`,
    popupUserAgreement: `User Agreement`,
    composition: `Composition`
  },

  'ru': {
    index: `Главная`,
    catalog: `Каталог`,
    deliveryPayment: `Доставка и оплата`,
    contacts: `Контакты`,
    forPartner: `Партнерам`,
    language: `Язык`,
    select: `RU`,
    becomePartner: `Стать партнером`,
    address: `309856, Белгородская обл., г. Алексеевка, тер. Опытная станция`,
    addressStart: `309856, Белгородская обл.,`,
    addressEnd: `г. Алексеевка, тер. Опытная станция`,
    production: `Производство`,
    ofEssentialOils: `эфирных масел`,
    essentialOils: `Эфирные масла`,
    essentialOil: `Эфирное масло`,
    essentialOilStart: `Эфирное`,
    essentialOilEnd: `масло`,
    essentialOilsText: `Только натуральные эфирные масла высокого качества, подтвержденного сертификатами`,
    ofSpices: `специй`,
    spices: `Специи`,
    spice: `Специя`,
    spicesText: `Мы обеспечиваем показатель очистки семян свыше 99% и производим помол различных фракций`,
    order: `Заказать`,
    aboutCompanyTitleStart: `Качество, помноженное`,
    aboutCompanyTitleEnd: `на традиции`,
    aboutCompanyDescription: `15 лет опыта производства натуральной продукции с использованием современных технологий и высоких экологических требований`,
    aboutCompanyBlock1: `Высокие стандарты качества, как следствие, высокое качество производимой продукции`,
    aboutCompanyBlock2: `Производство эфирных масел методом паровой дистилляции - самый эффективный метод получения натурального продукта`,
    aboutCompanyBlock3: `Уникальные методики лабораторных испытаний позволяют получить информацию о качестве масел и убедиться в отсутствии фальсификатов в процессе производства`,
    coriander: `Кориандр`,
    corianderStart: `Кори`,
    corianderEnd: `андр`,
    productFormDescription: `Наша компания может произвести эфирное масло, жмых, размол и очистку любых эфиромасличных культур`,
    seeds: `Зерно`,
    pressCake: `Жмых`,
    powder: `Молотый`,
    wholesaleTitleStart: `Продажа оптом`,
    wholesaleTitleEnd: `и в розницу`,
    wholesaleDescription: `Индивидуальная ценовая политика. Широкий ассортимент продукции, поставляемой партиями в различной упаковке от 10 мл до 180 кг`,
    feedbackIndexTitleStart: `Стать нашим`,
    feedbackIndexTitleEnd: `покупателем`,
    feedbackTitleStart: `Оставьте свои контактные данные`,
    feedbackTitleEnd: `и наш отдел продаж свяжется с вами в ближайшее время`,
    name: `Имя`,
    phoneNumber: `Номер телефона`,
    youMessage: `Ваше сообщение`,
    submit: `Отправить`,
    contactUs: `Связаться с нами`,
    howToUse: `Применение`,
    packaging: `Варианты упаковок`,
    certificateOfQuality: `Сертификат качества`,
    kraftBag: `Крафт пакет бумажный`,
    kraftBagCharacteristics: `от 100 до 500 г`,
    fleconBag: `Полипропиленовый (П/П) мешок`,
    fleconBagCharacteristics: `20 кг`,
    paperBag: `Бумажный мешок`,
    paperBagCharacteristics: `25 кг`,
    bigBag: `Мягкий контейнер (БИГ-БЭГ)`,
    bigBagCharacteristics: `От 500 до 850 кг`,
    powderWomen: `Молотая`,
    powderMan: `Молотая`,
    topGrade: `Высший сорт`,
    firstGrade: `1 сорт`,
    secordGrade: `2 сорт`,
    thirdGrade: `3 сорт`,
    glassPackaging: `Стеклянная и пластиковая тара`,
    glassPackagingCharacteristics: `от 10 мл до 10 кг`,
    steelBarrel: `Стальная закатная бочка`,
    steelBarrelCharacteristics: `вместимостью 180 кг`,
    essentialOilEn: ``,
    essentialOilRU: `Эфирное масло`,
    footerLogoStart: `Центр поддержки экспорта`,
    footerLogoEnd: `Белгородской области`,
    required: `Необходимо заполнить это поле`,
    deliveryBlock1Start: `После отправления заявки`,
    deliveryBlock1Body: `наш менеджер свяжется с вами в течение 1 часа`,
    deliveryBlock1End: `для уточнения деталей.`,
    deliveryBlock2Start: `Мы доставляем`,
    deliveryBlock2End: `нашу продукцию в любой город России, а также в страны ближнего и дальнего зарубежья собственным автопарком или с помощью транспортных компаний: КС «СДЭК», ТК «Деловые Линии», ООО «ПЭК». Мы поможем вам подобрать оптимальный способ доставки.`,
    deliveryBlock3Start: `Отгрузка`,
    deliveryBlock3End: `производится после 100% предоплаты в течение 1-5 рабочих дней.`,
    deliveryBlock4Start: `Для покупателей из других стран`,
    deliveryBlock4End: `доступна оплата через международный банковский перевод по системе SWIFT.`,
    npo: `ООО НПО «Алексеевское»`,
    popupSubmitTitle: `Оставить заявку`,
    popupCheckBox: `Даю согласие на обработку персональных данных согласно`,
    popupCheckBoxAnd: `и`,
    popupPrivacyPolicy: `политике конфидециальности`,
    popupUserAgreement: `пользовательскому соглашению`,
    composition: `Состав`
  },
};